// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.Server.DAL;

#nullable disable

namespace ProyectoFinal.Server.Migrations.Olimpiadas
{
    [DbContext(typeof(OlimpiadasContext))]
    partial class OlimpiadasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ProyectoFinal.Shared.Models.Olimpiadas", b =>
                {
                    b.Property<int>("OlimpiadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("BLOB");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resena")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoOlimpiadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.HasKey("OlimpiadaId");

                    b.ToTable("Olimpiadas");
                });

            modelBuilder.Entity("ProyectoFinal.Shared.Models.PeliculasDetalle", b =>
                {
                    b.Property<int>("DetalleOlimpiadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Participantes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OlimpiadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoOlimpiadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleOlimpiadaId");

                    b.HasIndex("OlimpiadaId");

                    b.ToTable("OlimpiadaDetalle");
                });

            modelBuilder.Entity("ProyectoFinal.Shared.Models.TipoOlimpiada", b =>
                {
                    b.Property<int>("TipoOlimpiadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Participantes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Disponible")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoOlimpiadaId");

                    b.ToTable("TipoOlimpiada");

                    b.HasData(
                        new
                        {
                            TipoPeliculaId = 1,
                            Actores = "",
                            Categoria = "Poesia",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 2,
                            Actores = "",
                            Categoria = "Ficcion",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 3,
                            Actores = "",
                            Categoria = "Autoayuda y desarrollo personal",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 4,
                            Actores = "",
                            Categoria = "Politica y Sociedad",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 5,
                            Actores = "",
                            Categoria = "Religion y Espiritualidad",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 6,
                            Actores = "",
                            Categoria = "Histórietas y Comics",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 7,
                            Actores = "",
                            Categoria = "Viajes y Aventuras",
                            Disponible = 0
                        },
                        new
                        {
                            TipoPeliculaId = 8,
                            Actores = "",
                            Categoria = "Infantil y Juvenil",
                            Disponible = 0
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Shared.Models.PeliculasDetalle", b =>
                {
                    b.HasOne("ProyectoFinal.Shared.Models.Olimpiadas", null)
                        .WithMany("olimpiadaDetalle")
                        .HasForeignKey("OlimpiadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinal.Shared.Models.Olimpiadas", b =>
                {
                    b.Navigation("olimpiadaDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
